version: '3.7'

services:
  mongo:
    image: ${MONGO_IMAGE}
    restart: always
    expose:
      - "${MONGO_PORT}"
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "${MONGO_VOLUME}:/data/db"
    container_name: opq-mongo
  nginx:
    image: ${NGINX_IMAGE}
    depends_on:
      - view
      - boxupdateserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & envsubst < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && nginx -g \"daemon off;\"'"
    environment:
      - NGINX_SERVER_NAME
      - NGINX_VIEW_PORT=${VIEW_PORT}
      - DOLLAR=$$
  certbot:
    image: ${CERTBOT_IMAGE}
    depends_on:
      - nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  view:
    image: ${VIEW_IMAGE}
    depends_on:
      - mongo
    restart: always
    ports:
      - "${VIEW_PORT}:${VIEW_PORT}"
    environment:
      - MONGO_URL=mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      - ROOT_URL=https://${NGINX_SERVER_NAME}
      - PORT=${VIEW_PORT}
      - METEOR_SETTINGS
  makai:
    image: ${MAKAI_IMAGE}
    depends_on:
      - mongo
    restart: always
    ports:
      - "9880:9880"
      - "8196:8196"
      - "8194:8194"
      - "9881:9881"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9899:9899"
      - "127.0.0.1:9884:9884"
    volumes:
      - "${MAKAI_VOLUME}:${MAKAI_VOLUME}"
    environment:
      - MAKAI_SETTINGS
      - ACQUISITION_BROKER_SETTINGS
      - TRIGGERING_BROKER_SETTINGS
  mauka:
    image: ${MAUKA_IMAGE}
    depends_on:
      - mongo
      - makai
    restart: always
    ports:
      - "9883:9883"
      - "9882:9882"
      - "12000:12000"
    volumes:
      - /:/hostfs:ro
    environment:
      - MAUKA_SETTINGS
  health:
    image: ${HEALTH_IMAGE}
    depends_on:
      - mongo
      - mauka
      - makai
      - view
    restart: always
    environment:
      - MONGO_URL=mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      - VIEW_URL=${HEALTH_VIEW_URL}
      - BOX_URL=${HEALTH_BOX_URL}
      - MAUKA_URL=${HEALTH_MAUKA_URL}
      - MAKAI_PUSH_URL=${HEALTH_MAKAI_PUSH_URL}
      - MAKAI_SUB_URL=${HEALTH_MAKAI_SUB_URL}
      - MAKAI_HEALTH_URL=${HEALTH_MAKAI_HEALTH_URL}
    volumes:
      - /tmp/opqhealth:/var/log/health
  boxupdateserver:
    image: ${BOXUPDATESERVER_IMAGE}
    restart: always
    expose:
      - "${BOXUPDATESERVER_HTTP_SERVER_PORT}"
    ports:
      - "${BOXUPDATESERVER_HTTP_SERVER_PORT}:${BOXUPDATESERVER_HTTP_SERVER_PORT}"
    environment:
      - BOX_UPDATE_SERVER_SETTINGS
    volumes:
      - "${BOXUPDATESERVER_UPDATES_DIR}:${BOXUPDATESERVER_UPDATES_DIR}:ro"
